#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           frontMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
turnLEDOn(dgtl12); //Turn LED On for debug
untilTouch(dgtl2); //wait until bumper switch touched
turnLEDOff(dgtl12); //Turn LED Off for debug
startMotor(port1, 127); //start Front Motor
startMotor(port2, 127); //Start Back Motor
wait(1); //wait to make sure off doesn't get triggered when turned on. NOTE MUST BE ON FOR I SEC BEFORE TURNED OFF
untilTouch(dgtl2); //wait until bumper switch pressed
turnLEDOn(dgtl12); //turn LED On for debug
stopMotor(port1); //turn Front Motor Off
stopMotor(port2); //turn Back Motor Off
}
