#pragma config(Motor,  port1, turn,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
startMotor(turn, 100);
wait(2);
stopMotor(turn);
}
