#pragma config(Motor,  port1,           bridgemotor,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
repeat(forever){
startMotor(port1, 100);
}

}
